version: '3'
services:
  app:
    image: 'node_v1'
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "1024m"
  
  nginx:
    image: nginx:latest
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "3"
        max-size: "1024m"
    ports: 
      - 80:80
      - 443:443 
    volumes:
      $PWD/src_docker/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      $PWD/src_docker/nginx.conf:/etc/nginx/nginx.conf